---
title: "regression"
author: "Bryan Ng, 2427348"
date: "2025-05-28"
output: pdf_document
---

```{r, warning=FALSE, include=FALSE}
library(lme4)
library(geepack)   
library(splines)
library(readr)
library(tidyr)
library(nlme)
library(tibble)
library(dplyr)
library(ggplot2)
library(car)
library(broom)
library(purrr)
library(knitr) 
```

```{r, warning=FALSE, include=FALSE}
df <- read_csv('C:/Users/ncwbr/Desktop/frmgham2.csv')
```

\section{Question 1}

```{r}
vars_q1 <- c("RANDID","SYSBP","DIABP","SEX","AGE","BMI","educ","TIME","PERIOD")
keep1 <- complete.cases(df[, vars_q1])
Q1_df <- df[keep1, vars_q1]
```

```{r, warning=FALSE}
Q1_SYSBP <- lme(
  SYSBP ~ SEX + AGE + BMI + educ + TIME + AGE:BMI + SEX:BMI,
  random = ~ TIME | RANDID,
  data = Q1_df,
  method = "REML",
  na.action = na.omit
)

df_diag <- data.frame(
  fitted = fitted(Q1_SYSBP),  
  resid  = residuals(Q1_SYSBP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()

ggplot(df_diag, aes(sample = resid)) +
  stat_qq() +
  stat_qq_line() +
  labs(
    title = "QQ‐plot of Residuals"
  ) +
  theme_minimal()

summary(Q1_SYSBP)
```

```{r}
Q1_DIABP <- lme(
  DIABP ~ SEX + AGE + BMI + educ + TIME + AGE:BMI + SEX:BMI,
  random = ~ TIME | RANDID,
  data  = Q1_df,
  method = "REML",
  na.action = na.omit
)

df_diag <- data.frame(
  fitted = fitted(Q1_DIABP),  
  resid  = residuals(Q1_DIABP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()

ggplot(df_diag, aes(sample = resid)) +
  stat_qq() +
  stat_qq_line() +
  labs(
    title = "QQ‐plot of Residuals"
  ) +
  theme_minimal()

summary(Q1_DIABP)
```

\section{Question 2}

```{r, include=FALSE}
vars_q2 <- c("BPMEDS","RANDID","SYSBP","DIABP","SEX","AGE","BMI","educ","TIME")
keep2 <- complete.cases(df[, vars_q2])
Q2_df <- df[keep2, vars_q2]
```

```{r}
ind <- geeglm(
  SYSBP ~ BPMEDS + AGE + BMI + TIME + SEX + educ
         + BPMEDS:SEX + BPMEDS:AGE + BPMEDS:BMI + BPMEDS:educ,
  id     = RANDID,
  data   = Q2_df,
  waves  = TIME,
  corstr = "independence",
  family = gaussian()
)

ar1 <- geeglm(
  SYSBP ~ BPMEDS + AGE + BMI + TIME + SEX + educ
         + BPMEDS:SEX + BPMEDS:AGE + BPMEDS:BMI + BPMEDS:educ,
  id     = RANDID,
  data   = Q2_df,
  waves  = TIME,
  corstr = "ar1",    
  family = gaussian()
)

exc <- geeglm(
  SYSBP ~ BPMEDS + AGE + BMI + TIME + SEX + educ + BPMEDS:SEX + BPMEDS:AGE + BPMEDS:BMI + BPMEDS:educ,
  id  = RANDID,
  data  = Q2_df,
  waves = TIME,
  corstr  = "exchangeable",
  family  = gaussian()
)
QIC(ind);QIC(ar1);QIC(exc)
```

```{r, warning=FALSE}
Q2_SYSBP <- geeglm(
  SYSBP ~ BPMEDS + AGE + BMI + TIME + SEX + educ + BPMEDS:SEX + BPMEDS:AGE + BPMEDS:BMI + BPMEDS:educ,
  id  = RANDID,
  data  = Q2_df,
  waves = TIME,
  corstr  = "independence",
  family  = gaussian()
)

df_diag <- data.frame(
  fitted = fitted(Q2_SYSBP),  
  resid  = residuals(Q2_SYSBP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()

summary(Q2_SYSBP)
```



```{r}
Q2_DIABP <- geeglm(
  DIABP ~ BPMEDS + AGE + BMI + TIME + SEX + educ + BPMEDS:SEX + BPMEDS:AGE + BPMEDS:BMI + BPMEDS:educ,
  id  = RANDID,
  data  = Q2_df,
  waves   = TIME,
  corstr  = "independence",
  family  = gaussian()
)

df_diag <- data.frame(
  fitted = fitted(Q2_DIABP),  
  resid  = residuals(Q2_DIABP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()

summary(Q2_DIABP)
```

\section{Question 3}

```{r}
df$CIGPDAY <- log(df$CIGPDAY + 1)
vars_q3 <- c("RANDID","SYSBP","DIABP",
             "CURSMOKE","CIGPDAY","SEX","AGE","BMI","educ","BPMEDS","TIME")
keep3 <- complete.cases(df[, vars_q3])
Q3_df <- df[keep3, vars_q3]
```

```{r}
ind <- geeglm(
  SYSBP ~ BPMEDS + AGE + BMI + TIME + SEX + educ + CIGPDAY + CURSMOKE
         + CURSMOKE:SEX + CIGPDAY:SEX + CURSMOKE:BPMEDS,
  id     = RANDID,
  data   = Q3_df,
  waves  = TIME,
  corstr = "independence",
  family = gaussian()
)

ar1 <- geeglm(
  SYSBP ~ BPMEDS + AGE + BMI + TIME + SEX + educ + CIGPDAY + CURSMOKE
         + CURSMOKE:SEX + CIGPDAY:SEX + CURSMOKE:BPMEDS,
  id     = RANDID,
  data   = Q3_df,
  waves  = TIME,
  corstr = "ar1",    
  family = gaussian()
)

exc <- geeglm(
  SYSBP ~ BPMEDS + AGE + BMI + TIME + SEX + educ + CIGPDAY + CURSMOKE + CURSMOKE:SEX + CIGPDAY:SEX + CURSMOKE:BPMEDS,
  id  = RANDID,
  data  = Q3_df,
  waves = TIME,
  corstr  = "exchangeable",
  family  = gaussian()
)
QIC(ind);QIC(ar1);QIC(exc)
```

```{r}
Q3_SYSBP <- geeglm(
  SYSBP ~ CIGPDAY + CURSMOKE + AGE + BMI + BPMEDS + TIME + SEX + educ + CURSMOKE:SEX + CIGPDAY:SEX + CURSMOKE:BPMEDS,
  id = RANDID,
  data  = Q3_df,
  waves = TIME,
  corstr = "independence",
  family = gaussian()
)

df_diag <- data.frame(
  fitted = fitted(Q2_SYSBP),  
  resid  = residuals(Q2_SYSBP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()
summary(Q3_SYSBP)
```

```{r}
Q3_DIABP <- geeglm(
  DIABP ~ CIGPDAY + CURSMOKE + AGE + BMI + BPMEDS + TIME + SEX + educ + CURSMOKE:SEX + CIGPDAY:SEX + CURSMOKE:BPMEDS,
  id  = RANDID,
  data  = Q3_df,
  waves = TIME,
  corstr  = "independence",
  family  = gaussian()
)

df_diag <- data.frame(
  fitted = fitted(Q3_DIABP),  
  resid  = residuals(Q3_DIABP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()
summary(Q3_DIABP)
```


\section{Question 4}

```{r}
vars_q4 <- c("RANDID","SYSBP","DIABP",
             "TOTCHOL","GLUCOSE",
             "SEX","AGE","BMI","educ","BPMEDS","CURSMOKE","CIGPDAY","TIME")
keep4   <- complete.cases(df[, vars_q4])
Q4_df   <- df[keep4, vars_q4]
```

```{r, warning=FALSE}
Q4_SYSBP <- lme(
  fixed = SYSBP ~ TOTCHOL + GLUCOSE + AGE + BMI + BPMEDS + SEX + educ + CIGPDAY + CURSMOKE + TOTCHOL:SEX + GLUCOSE:SEX + TOTCHOL:AGE + GLUCOSE:AGE + TOTCHOL:BMI + GLUCOSE:BMI + TOTCHOL:CURSMOKE + GLUCOSE:CURSMOKE + TOTCHOL:BPMEDS + GLUCOSE:BPMEDS,
  random = ~ TIME | RANDID,
  data = Q4_df,
  method = "REML",
  na.action = na.omit
)

df_diag <- data.frame(
  fitted = fitted(Q4_SYSBP),  
  resid  = residuals(Q4_SYSBP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()

ggplot(df_diag, aes(sample = resid)) +
  stat_qq() +
  stat_qq_line() +
  labs(
    title = "QQ‐plot of Residuals"
  ) +
  theme_minimal()

summary(Q4_SYSBP)
```

```{r}
Q4_DIABP <- lme(
  fixed = DIABP ~ TOTCHOL + GLUCOSE + AGE + BMI + BPMEDS + CURSMOKE + CIGPDAY + SEX + educ + TOTCHOL:SEX + GLUCOSE:SEX + TOTCHOL:AGE + GLUCOSE:AGE + TOTCHOL:BMI + GLUCOSE:BMI + TOTCHOL:CURSMOKE + GLUCOSE:CURSMOKE + TOTCHOL:BPMEDS + GLUCOSE:BPMEDS,
  random = ~ TIME | RANDID,
  data = Q4_df,
  method = "REML",
  na.action = na.omit
)

df_diag <- data.frame(
  fitted = fitted(Q4_SYSBP),  
  resid  = residuals(Q4_SYSBP)      
)
ggplot(df_diag, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Fitted values",
    y = "Residuals",
    title = "Residuals vs Fitted"
  ) +
  theme_minimal()

ggplot(df_diag, aes(sample = resid)) +
  stat_qq() +
  stat_qq_line() +
  labs(
    title = "QQ‐plot of Residuals"
  ) +
  theme_minimal()

summary(Q4_DIABP)
```

```{r}
models <- list(
  Q1_SYSBP = Q1_SYSBP,
  Q1_DIABP = Q1_DIABP,
  Q2_SYSBP = Q2_SYSBP,
  Q2_DIABP = Q2_DIABP,
  Q3_SYSBP = Q3_SYSBP,
  Q3_DIABP = Q3_DIABP,
  Q4_SYSBP = Q4_SYSBP,
  Q4_DIABP = Q4_DIABP
)

extract_coefs <- function(fit) {
  if (inherits(fit, "geeglm")) {
    
    mat <- summary(fit)$coefficients
    df  <- as.data.frame(mat, check.names = FALSE)
    df$term <- rownames(df)
    df %>%
      rename(
        estimate  = Estimate,
        std.error = `Std.err`,
        statistic = Wald,
        p.value   = `Pr(>|W|)`
      ) %>%
      select(term, estimate, std.error, statistic, p.value)
  } else if (inherits(fit, "lme")) {
    
    mat <- summary(fit)$tTable
    df  <- as.data.frame(mat, check.names = FALSE)
    df$term <- rownames(df)
    df %>%
      rename(
        estimate  = Value,
        std.error = `Std.Error`,
        statistic = `t-value`,
        p.value   = `p-value`
      ) %>%
      select(term, estimate, std.error, statistic, p.value)
  } else {
    stop("Extractor only knows geeglm and lme")
  }
}

coef_tables <- map(models, extract_coefs)

walk2(
  coef_tables,
  names(coef_tables),
  ~{
    cat("## Model:", .y, "\n\n")
    print(
      kable(
        .x,
        caption   = paste("Coefficients for", .y),
        digits    = 3,
        col.names = c("Term","Estimate","Std.Error","Stat","p.value")
      )
    )
    cat("\n\n")
  }
)
```

